obstacle_range: 0.01
raytrace_range: 0.01
footprint: [[0.3, 0.3],[0.4, 0], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
robot_radius: 0.03
inflation_radius: 0.3
transform_tolerance: 0.4

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
